version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_HOST=$DB_HOST
        - DB_PORT=$DB_PORT
        - DB_DATABASE=$DB_DATABASE
        - DB_USERNAME=$DB_USERNAME
        - DB_PASSWORD=$DB_PASSWORD
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backapi
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
